### ISSUE TITLE
Problem With Path On Windows

### ISSUE THREAD

**Issue by jeffscottbrown** [theratpack/grails-zap-security-tests-plugin#8]
On Windows I am seeing the following:

```
| Configuring ZAP Security Tests plugin...
| Server stopped
| Error Fatal error running tests: C (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.net.UnknownHostException: C
        at _ZapSecurityTests_groovy$_run_closure3.doCall(_ZapSecurityTests_groovy:57)
        at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
        at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy:185)
        at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16_closure18.doCall(GantBinding.groovy)
        at org.codehaus.gant.GantBinding.withTargetEvent(GantBinding.groovy:90)
        at org.codehaus.gant.GantBinding.this$4$withTargetEvent(GantBinding.groovy)
        at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy:185)
        at org.codehaus.gant.GantBinding$_initializeGantBinding_closure5_closure16.doCall(GantBinding.groovy)
        at _ZapSecurityTests_groovy$_run_closure13.doCall(_ZapSecurityTests_groovy:165)
        at _ZapSecurityTests_groovy$_run_closure13.doCall(_ZapSecurityTests_groovy)
        at _Events$_run_closure1.doCall(_Events.groovy:35)
        at _GrailsTest$_run_closure1.doCall(_GrailsTest.groovy:102)
```

**Comment by luque** [comment]
Hi Jeff. Unfortunately I have not any Windows box available right now. However I've just tried to fix the bug blindly. You can find the change in the issue5 branch I have just pushed. Please let me know if you can try this new version. Thank you!
